### ISSUE TITLE
Corrupt DGTA_SeaDroneSee/train/images.tar.gz file!

### ISSUE THREAD

**Issue by sagarverma** [Eisbaer8/DeepGTAV#11]
I tried downloading the [DGTA_SeaDroneSee/train/images.tar.gz](https://cloud.cs.uni-tuebingen.de/index.php/s/cQ3Qt5z8o4e5GWo?path=%2FDGTA_SeaDronesSee%2Ftrain). The file seems to be corrupt.

**Comment by Ben93kie** [comment]
I downloaded it and it worked fine. There seems to be a "compatibility" issue when opening it with either the file explorer or after unzipping it using the file explorer. If you open up the zip file without uncompressing it, you should see all intact images. Try to use a different method to unzip, that might work. Let me know if that helped.

**Comment by sagarverma** [comment]
I tried it on Chrome on Windows and Mac, Edge on Windows, and curl on Ubuntu. The file downloads immediately and on disk its 0 byte. I have added a loom link and screenshots. 

I have downloaded the other two synthetic dataset and they are of similar size.  

https://www.loom.com/share/ce7c7d51bab5471db2227034f5b735cd
![Screenshot 2022-10-06 222056](https://user-images.githubusercontent.com/2713531/194410899-7f25a2e8-6da9-4640-8ccb-caacb8c7dfff.png)

![Screenshot 2022-10-06 222638](https://user-images.githubusercontent.com/2713531/194411818-8c19f53a-ef5e-4f5b-baea-a132e83bb210.png)

**Comment by Ben93kie** [comment]
Thanks for your feedback. Indeed, I also tried it again and it did not work.
I highly recommend that you use the DGTA_SeaDronesSee_jpg version. Although it is "only" of FullHD resolution, this is very sufficient for most use cases and the compression does not seems to impact the performance significantly. 

Anyways, I'm reuploading the complete version currently. This can take several hours though and might fail, so I would not bet on it the next day (but hopefully it worked by the end of the week).

**Comment by Ben93kie** [comment]
Should be up and working again. Let me know if not.
