### ISSUE TITLE
I am curious about the format of the metadata.

### ISSUE THREAD

**Issue by jongphago** [Eisbaer8/DeepGTAV#3]
Hello.
Thank you for the good research results you showed using synthetic data.

I would like to ask for information about the format of metadata.

The pre-generated dataset you posted was very helpful to me.
Thank you.

```plaintext
<Sample of meta data>
a: -425.1471252441406
b: -559.9451293945312 
c: 77.26197814941406 
d: 50.85673904418945 
e: -427.5518493652344 
f: -558.969970703125 
g: 57.43088912963867 
h: -81.8794174194336 
i: -6.996013164520264 
j: 137.6229705810547 
k: 17 
l: 0 
m: 36 
n: EXTRASUNNY
```

**Comment by Eisbaer8** [comment]
Hello.

The format of the metadata is:

[x y z heightAboveGround, campos_x, campos_y, campos_z, camrot_x, camrot_y, camrot_z, time_hours, time_min, time_sec, weather]

`x,y,z`: the location of the player vehicle in GTAV world coordinates.
`heightAboveGround`: The height difference of the player vehicle to the ground (or water)
`campos_x, campos_y, campos_z`: The positions of the camera in world coordinates.
`camrot_x, camrot_y, camrot_z`: The camera rotations
`time_hours, time_min, time_sec`: The ingame time
`weather`: the ingame weather condition


Note that the camera position in general is offset wrt. the player vehicle. Also the height of the camera above ground is different from the heightAboveGround for the vehicle, so if you need this you need to calculate it.
