### ISSUE TITLE
understanding camera rotation

### ISSUE THREAD

**Issue by fabiopoiesi** [Eisbaer8/DeepGTAV#8]
Hi,

I am trying to understand how to interpret the camera orientation parameters: `camrot_x, camrot_y, camrot_z`.
Is the camera fixed to the drone (i.e. there is no gimbal)?
Which axis is the view direction?

For example, in this case the z axis is view direction:
![4iFEV](https://user-images.githubusercontent.com/17005352/175226324-d0bc8bbf-ff5a-4648-8007-376a55c260cc.png)

I am asking this because I would like to understand from the metadata when the camera is pointing down or at the horizon.

Thanks!

**Comment by Eisbaer8** [comment]
Hey,

the camera orientation parameters `camrot_x, camrot_y, camrot_z` in the meta_data are given relative to the world coordinates. 
If you are familiar with ScriptHookV those are the returns of CAM::GET_CAM_ROT(camera, 0);

They can be understood as `pitch, roll, yaw` relative to the world coordinates. (i.e. `camrot_x` corresponds to `pitch`, `camrot_y` to `roll` and `camrot_z` to `yaw`. 
Note however that they are applied in the order `camrot_z` -> `camrot_x` -> `camrot_y`. That is, we first do the `yaw` rotation, then the `pitch` rotation and finally the `roll` rotation. 

So the Y-Axis is the viewing direction.

For most applications the only relevant information is the `camrot_x` that gives the camera pitch, which is the camera angle relative to the horizon. 

A camera looking directly downwards corresponds to `camrot_x = -90`
A camera looking directly at the horizon corresponds to `camrot_x = 0`

**Comment by C-der-Baum** [comment]
I guess this is answered. Let me know if not.
