### ISSUE TITLE
road semgentation and multiple side-view cameras

### ISSUE THREAD

**Issue by eliabruni** [Eisbaer8/DeepGTAV#9]
Hello,

Great work!

I have two questions:

1. Do you think it would be possible to obtain also road segmentation (e.g., drivable/non drivable)?
2. Do you think it would be possible to mount multiple side-view cameras on top of a car while also getting the aerial view?

Thanks!

**Comment by Eisbaer8** [comment]
Hey,

1. I don't know of an easy way that this would be possible. In general the segmentation information is obtained from the stencil buffer of the GTAV rendering pipline. As I recall the roads don't have an individual stencil mask, so this would not be easy. For more information you can look into https://www.adriancourreges.com/blog/2015/11/02/gta-v-graphics-study/


2. Yes it would be possible to get additional camera views. To do this one would need to add additional cameras in the DataExport.cpp and while having the game paused for the capture one would need to switch to the different active cameras, capture the image + data from their view, then switch to the next, capture from their view and so on. Finally one would transfer all the data by adding it to the message. 
This is possible, however it is quite some coding work.

If you actually implement this, a pull request would be much appreciated :D

**Comment by eliabruni** [comment]
Hello @Eisbaer8 , many thanks for the clarifications! I will look into it and, of course, I'll do a PR if I manage to implement it.

Cheers

**Comment by GANWANSHUI** [comment]
Hi, @eliabruni. I also have an interest in seeing the second question you mentioned. Was there any progress from your side? Thanks a lot!

> Do you think it would be possible to mount multiple side-view cameras on top of a car while also getting the aerial view?

**Comment by eliabruni** [comment]
Hey @GANWANSHUI , not really, unfortunately. It seems quite a task the way I see it.
